### PR TITLE
Remove extraneous '^'; introduced by wiki to MD conversion?

### PR DESCRIPTION
**Pull request by RetroEdit**

### CODE REVIEW

**Comment by avivace** [comment]
Thanks @RetroEdit ! Is this happening somewhere else?

**Comment by RetroEdit** [comment]
I did a grep and didn't find any '^'; there could be similar artifacts from tags in the wiki, potentially (haven't downloaded and grepped wiki yet). Essentially the problem appears to come from `2<sup>22</sup>` being converted to `2^22^`.

What converter was used to turn the wikitext into Markdown?

**Comment by avivace** [comment]
Oh okay, makes sense.
The export from mediawiki and conversion to pandoc is handled by the scripts here: https://github.com/gbdev/pandocs/tree/develop/mediawiki-exporter

The XML -> Markdown conversion is done via pandoc

**Comment by RetroEdit** [comment]
Ah, [pandoc](https://pandoc.org/), not this Pan Docs. I was a bit confused until I looked at the Python code for processing the MediaWiki XML export.

**Comment by avivace** [comment]
@RetroEdit markdown-pp is only doing the "merge", the actual rendering (for the web version) is handled by vuepress

**Pull request merged**
