### PR TITLE
Correcting the mode select and adding information about MBC1 multi-ga…

### PR DESCRIPTION
**Pull request by TheThief**
…me carts

### CODE REVIEW

**Comment by mattrberry** [comment]
I would clarify that there are 2 banking registers that are being updated independently. That wasn't immediately obvious to me. I'd also specify that the first register defaults to 1. Still, this was useful to me in implementing proper MBC1 functionality!

**Comment by avivace** [comment]
@TheThief do you think you can incorporate @mattrberry suggestion somewhere?

**Comment by TheThief** [comment]
I've had a go at clarifying a few things

**Comment by avivace** [comment]
Looks pretty good to me!

**Comment by mattrberry** [comment]
@TheThief @avivace I know this is already in develop, but I still think it'd be useful to specify that the rom banking number defaults to 1. I feel like the standard assumption would be that they'd both default to 0, but the rom banking number breaks that assumption. That caused a bug in _my_ emulator when I was implementing MBC1, and the only way I figured it out was by asking @TheThief on discord.

All of the other changes look great!

**Comment by TheThief** [comment]
That is actually mentioned now!

**Comment by mattrberry** [comment]
Ah, I read past that! Looks good!

**Comment by avivace** [comment]
:tada:

**Pull request merged**
