### PR TITLE
Modify description of LCDC bit 0

### PR DESCRIPTION
**Pull request by AlvaroBurnett**

### CODE REVIEW

**Comment by CasualPokePlayer** [comment]
This isn't really accurate (and is inconsistent with a later part of the docs). The meaning is more BG Display or BG and Window Priority. https://gbdev.io/pandocs/#lcdc-0-bg-window-display-priority

**Comment by ISSOtm** [comment]
When that bit is clear on DMG, the BG FIFO is disabled, but that also causes the window not to be displayed. Hence, the later part of the docs is actually wrong.

By the way, wouldn't it be nicer if the rows linked to the relevant anchors?

**Comment by AlvaroBurnett** [comment]
Is it ok if we replace "Non-CGB Mode" with "DMG Mode"?

**Comment by ISSOtm** [comment]
The problem is that on one hand there's CGB (and AGB) in Color mode, and OTOH there's everything else. How is that "everything else" best referred to?

**Comment by AlvaroBurnett** [comment]
Is there any difference between the Non-CGB mode of the CGB and the Non-CGB mode of the AGB?

**Comment by ISSOtm** [comment]
None significant, if any.

**Review by ISSOtm — APPROVED** [review]

**Pull request merged**
