### PR TITLE
Clarify that setting SC bit 7 is mandatory on slave to accept a Serial Data Transfer

### PR DESCRIPTION
**Pull request by avivace**
See https://github.com/gbdev/pandocs/issues/398

@quinnyo @ISSOtm @jbshelton

### CODE REVIEW

**Comment by quinnyo** [comment]
I think this looks good to merge, but there are some other instances of the same issue elsewhere on the page: in the intro and the very last paragraph (under 'Delays and Synchronization'). I don't know if you want to fix them as part of this PR or separately?

**Comment by avivace** [comment]
> I think this looks good to merge, but there are some other instances of the same issue elsewhere on the page: in the intro and the very last paragraph (under 'Delays and Synchronization'). I don't know if you want to fix them as part of this PR or separately?

I'd say let's handle them all in this PR? I just pushed some more changes

**Review by ISSOtm — APPROVED** [review]
I'm now wondering what value is obtained from attempting a transfer when the other GB(C) has not set its bit 7. Could it depend on the last transferred bit?

**Comment by avivace** [comment]
> I'm now wondering what value is obtained from attempting a transfer when the other GB(C) has not set its bit 7. Could it depend on the last transferred bit?

maybe you can open a new 'research' issue regarding this?

**Pull request merged**
