### PR TITLE
Revise the explanation of the cartridge header (continued)

### PR DESCRIPTION
**Pull request by avivace**
Follow up of https://github.com/gbdev/pandocs/pull/422

### CODE REVIEW

**Comment by avivace** [comment]
See points in https://github.com/gbdev/pandocs/pull/422#pullrequestreview-1048684969

**Comment by ihonen** [comment]
I incorporated the changes suggested in #422. I also went through the entire document one more time and fixed whatever inconsistencies and such I could find. I squashed all the changes suggested in earlier reviews into a single commit, so there are now 3 commits in this PR: my original commit, the changes suggested in #422 and my latest clean-up commit.

Regarding the supposedly premature merging of the previous PR, I'll point out that I don't think that is a fair assessment as there were in fact no more unaddressed issues _at the time_ @ISSOtm did the merge, so it's hardly his fault.

Regardless, feel free to conduct any further reviewing, but as far as I am concerned this PR is ready for merge.

P.S. I'm not sure if the changes suggested by @ISSOtm in #422 to `src/Power_Up_Sequence.md` are relevant to this PR, so I did not include those (yet).

**Comment by ihonen** [comment]
I incorporated the changes suggested in https://github.com/gbdev/pandocs/pull/422. I also went through the entire document one more time and fixed whatever inconsistencies and such I could find, as well as fixed the broken links. The changes suggested in earlier reviews have now been squashed into a single commit.

Regarding the supposedly premature merging of the previous PR, I'll point out that I don't think that is a fair assessment as there were in fact no more unaddressed issues at the time @ISSOtm did the merge, so it's hardly his fault.

Regardless, feel free to conduct any further reviewing, but as far as I am concerned this PR is ready for merge.

**Review by avivace — COMMENTED** [review]
Thanks a lot for sticking with this @ihonen !

It looks great now, I guess we just need to revert the `-` -> `—` changes, as they also break links..

**Comment by ihonen** [comment]
> It looks great now, I guess we just need to revert the - -> — changes, as they also break links..

I suppose you mean that we would have to fix every link that references one of the changed headers? Because I did that, at least to the best of my abilities, by searching for every instance of the old title in the source and replacing it with the new one.

It's no big deal to undo the change if you want me to, but I did my best to make the new titles work as well, so whichever you prefer.

**Comment by avivace** [comment]
> > It looks great now, I guess we just need to revert the - -> — changes, as they also break links..
> 
> I suppose you mean that we would have to fix every link that references one of the changed headers? Because I did that, at least to the best of my abilities, by searching for every instance of the old title in the source and replacing it with the new one.
> 
> It's no big deal to undo the dash change if you want me to, but I did my best to make the new titles work as well, so whichever you prefer. I just thought en dashes looked better, and also it's the correct dash to use in ranges (such as address ranges), so I went for it.

The issue here is that changing dashes changes and breaks all the links outside of our control, and it's a change that should be discussed in a different PR. If we decide to switch to another dash, we should apply that globally to the entire document. 

Let's bring back the PR on the scope and open another one to decide about the titles

**Comment by ihonen** [comment]
That's a good point about external links.

Should I undo all other changes in the header titles as well? For example, I changed `Mask ROM Version number` -> `Mask ROM Version Number` (to be fair, I think that's the only non-dash change).

**Comment by ihonen** [comment]
Alright, I undid the title changes. Feel free to merge. :)

**Pull request merged**
