### PR TITLE
Missing register values for different GB models

### PR DESCRIPTION
**Pull request by nefenit**
I found those values in historical versions of pandocs (gbspec.txt) and GB CPU Manual v 1.01.
"Detecting CGB (and GBA) functions " has both A = $11 in GBC/GBA and B = $01 in GBA  mentioned but is missing here.
This error probably occured because someone copy-pasted "Power Up Sequence" page from gbdev.gg8.se wiki which is incomplete.

### CODE REVIEW

**Comment by CasualPokePlayer** [comment]
see https://github.com/gbdev/pandocs/issues/211

**Comment by nefenit** [comment]
dmg_bootrom.gb (DMG-01) last 2 lines of disassembly:
  LD A, $01
  LD $($FF00+$50), A
mgb_boot.bin (MGB-001) 2 last lines of disassembly:
  LD A,$FF
  LD ($FF00+$50),A

A = $01-GB, $FF-GBP
This behaviour is consistent and should be added.
In issue #211 it seems that it affects CGB in compatibility mode someone should check it.
A = $11 in GBC/GBA and B = $01 adding that to "Power Up Sequence" makes sense because this information should be in one place and not scared around.

**Comment by ISSOtm** [comment]
Are you sure about all these values when selecting a CGB palette for DMG ROMs?

**Comment by nefenit** [comment]
no, i don't know how they would behave

**Comment by CasualPokePlayer** [comment]
A=$11 is constant, although the B=$01 is not. B can wildy change in DMG compatibility mode w/ Licensee (the title checksum meant for the predefined palettes for DMG games is left onto B, causing in theory any possible value for B). Also, manually changing palettes does not affect any registers, this can easily be confirmed with a bit of manual testing. The old logo tilemap being written could have an effect but I have not tested it.

**Comment by nefenit** [comment]
I didn't knew that @CasualPokePlayer thanks for explaining
In GB Prog manual 1.0 i found on page 120 that A values are consistent across models
they also match up with what i found using boot ROMs and in previously found files
```
A = 0x01-GB/SGB, 0xFF-GBP/GBL/SGB2, 0x11-CGB
```
Would adding only that part be ok?

**Review by avivace — APPROVED** [review]

**Comment by CasualPokePlayer** [comment]
> 
> 
> A=$11 is constant, although the B=$01 is not. B can wildy change in DMG compatibility mode w/ Licensee (the title checksum meant for the predefined palettes for DMG games is left onto B, causing in theory any possible value for B). Also, manually changing palettes does not affect any registers, this can easily be confirmed with a bit of manual testing. The old logo tilemap being written could have an effect but I have not tested it so I can't say for certain.

Doing some more tests, it does appear the old logo tilemap being written does change registers. Keep in mind you can only get the old logo tilemap written if you have the Nintendo Licensee bytes in the header along with DMG mode there too, so AF, BC, and DE will be identical to that situation (although, even then, there's only 2 versions of B possible here). However, HL will be different:
`HL: 991A`

The A value is an absolute constant so it's probably fine to include that in there, although you should use MGB instead of GBP, as GBP can also refer to the Game Boy Player (which the only usage of GBP in the Pandocs refers to the Game Boy Player in that context, with the GameBoy Pocket being referred to as MGB everywhere else).

**Comment by avivace** [comment]
@ISSOtm what's the status on this?

**Comment by ISSOtm** [comment]
Still needs some work, and I currently don't have time to do it myself.

**Comment by ISSOtm** [comment]
I'll try to make a separate PR adding this info and more initial reg state (partial overlap with #309, so that it could be used as a reference for that), and improving the section's formatting.

**Pull request closed without merging**
