### PR TITLE
Plot generation: move to matplotlib, make output SVGs affected by CSS theme

### PR DESCRIPTION
**Pull request by avivace**
It may seem a bit convoluted, but it works:

https://user-images.githubusercontent.com/14352721/201120995-a3bf61d5-e9f6-472f-ba4a-b150bfb8c9dd.mp4

Some more stuff is needed to merge this but we should be already at a pretty good point:

- [x] move from pygal to matplotlib https://github.com/gbdev/pandocs/issues/449
- [x] make the output SVG use the CSS variables instead of hardcoded colros
- [ ] update requirements.txt
- [ ] move the call to the plot generation from the `renderer` to the `preproc` step of mdbook, otherwise the output SVG files cannot be inline injected
	- We should consider just calling a python script, instead of having the single calls for every plot like it is now [here](https://github.com/gbdev/pandocs/blob/master/book.toml#L16). @ISSOtm opinions?
- [ ] replace the two img tags with #import in the MBC5 article so the svg is actually injected in the HTML

Fixes https://github.com/gbdev/pandocs/issues/322

### CODE REVIEW

**Comment by alloncm** [comment]
I might be missing something but why not use a Rust plotting library instead of calling a python script from the Rust renderer?
This way you can remove Python from the dependencies and maybe make the deployment easier.

The only reason I can think of is that Rust simply don't have a good plotting library with support for SVG's (but this looks like a good one - https://github.com/plotters-rs/plotters)

**Comment by ISSOtm** [comment]
I swear I have seen a comment somewhere about using a Rust plotter instead to cut on the dependencies, suggesting https://github.com/plotters-rs/plotters, but I can't find it anymore.

**Comment by ISSOtm** [comment]
The rationale for moving to a Rust library instead is to remove a contribution barrier, by using simpler setup instructions (no virtualenv) that work on all systems.

As for matplotlib itself, while you have a point that it is more popular, I can't say it's more standard—its documentation is very vague and confusing, and I have never seen two StackOverflow answers agreeing on a strategy to using it... :/

Besides, someone can always contribute a different setup later if they don't like the one we end up adopting, and it can use Python if they're willing to test their instructions. I don't think a move would be a blocker for that?

**Comment by avivace** [comment]
> The rationale for moving to a Rust library instead is to remove a contribution barrier, by using simpler setup instructions (no virtualenv) that work on all systems.

Python is not mandatory to contribute, one can simply skip the plot generations. If someone desires can provide a plot generated with a rust program instead, too.

> As for matplotlib itself, while you have a point that it is more popular, I can't say it's more standard—its documentation is very vague and confusing, and I have never seen two StackOverflow answers agreeing on a strategy to using it... :/

I don't see how this is a negative points, it's okay if you have a lot of ways to do something.

> Besides, someone can always contribute a different setup later if they don't like the one we end up adopting, and it can use Python if they're willing to test their instructions. I don't think a move would be a blocker for that?

Did you check this PR? Imagine translating all the logic I added to parse SVGs to make them affected by CSS translated in Rust. I (personally) am not going to do that or ask anyone to go through that to contribute a plot. Python is super declarative and the matplotlib part is all self-declarative.

**Comment by ISSOtm** [comment]
Spring has ended a few weeks ago, but pollen levels are still at a record high so it's still spring cleaning time if you ask me. Rebased (to check for any merge conflicts). Re-reading the arguments, sure, let's go with Python. We can consider moving to a Rust lib if at all later, that bikeshedding should not block this improvement.

We can't use `{{#include}}` tags for this without adding a new preproc step, because the `"links"` preproc is what processes these tags. Our custom preproc runs after it so that it can process transcluded fragments.

A possibility is making our custom preproc process e.g. `{{#plot}}` tags, which would invoke the Python script and replace the tag with the script's output. Then I think we can have the best of both worlds!

**Pull request closed without merging**
