### PR TITLE
Fix broken discord link and readme typos

### PR DESCRIPTION
**Pull request by rmccorm4**
- Fix broken Discord link from [old link](https://discord.gg/9wBRWWT) to [new link](https://discord.gg/tKGMPNr) taken from https://gbdev.io/chat.html
- Fix minor typos

### CODE REVIEW

**Comment by JL2210** [comment]
I would link to the gbdev.io page instead, so the link won't break

**Comment by avivace** [comment]
Great! Thanks @rmccorm4 . I'd use the https://gbdev.io/chat.html link instead of directly linking the chat, as @JL2210 suggested, since we are using that "landing page" to keep invite links changes.

**Comment by rmccorm4** [comment]
Sure - Replaced Discord/IRC links with parent page https://gbdev.io/chat.html as mentioned above.

**Review by ISSOtm — APPROVED** [review]
Considering that all raised objections have been fixed and this looks OK, merging.

**Comment by avivace** [comment]
Great, thanks!

**Pull request merged**
