### PR TITLE
LCDC7: describe PPU

### PR DESCRIPTION
**Pull request by AlvaroBurnett**

### CODE REVIEW

**Review by ISSOtm — CHANGES_REQUESTED** [review]
Imo the PPU *should* be described somewhere in the docs, but rather in a dedicated "system architecture" section at the top, not here. This is because it's a term, along with e.g. "APU", which is references all around the document.

**Comment by AlvaroBurnett** [comment]
I understand. Should we place this description in one of the existing files, or maybe create a new one named "System_Architecture.md"?

**Comment by ISSOtm** [comment]
Good question...

**Comment by avivace** [comment]
> Imo the PPU _should_ be described somewhere in the docs, but rather in a dedicated "system architecture" section at the top, not here. This is because it's a term, along with e.g. "APU", which is references all around the document.

I agree

> I understand. Should we place this description in one of the existing files, or maybe create a new one named "System_Architecture.md"?

New file is better, so we can import it somewhere in the introductory part and give some context

**Review by avivace — CHANGES_REQUESTED** [review]
Move to another file

**Comment by AlvaroBurnett** [comment]
Replaced with a proper PR.

**Pull request closed without merging**
