### PR TITLE
Touch up SGB packet documentation

### PR DESCRIPTION
**Pull request by ISSOtm**
Turn the diagram into a SVG, and reformat/improve the doc.

### CODE REVIEW

**Review by avivace — CHANGES_REQUESTED** [review]
It seems like the base text size is a bit too big compared to the rest, it should be 120-140% of the base.

image

**Comment by ISSOtm** [comment]
Being that this is a SVG which automatically scales to the device width, there isn't really control over that. Compare Firefox's "Responsive" view simulating a phone screen:

Screenshot showing the diagram with a wildly different proportion

Is it a big deal?

**Comment by avivace** [comment]
I think shouldn't, check for example how https://gbdev.io/pandocs/Rendering.html#ppu-modes behaves, there is a limit on how "big it can become" while being free to get as small as possible preserving the layout when seen from smaller viewports..

**Comment by ISSOtm** [comment]
The same width limit applies to this diagram; though, perhaps what you're saying is that the proportions of the text versus the rest of the diagram are wrong?

Note that the PPU mode diagram becomes tiny on mobile screens, though; not that I believe anything can be done about that?

Screenshot of the aforementioned diagram rendered on a mobile screen

**Comment by avivace** [comment]
> The same width limit applies to this diagram; though, perhaps what you're saying is that the proportions of the text versus the rest of the diagram are wrong? That I could fix.

Yep, I would say that should fix it

**Comment by ISSOtm** [comment]
Then you can try playing with the proportions by adjusting `font-size` in the SVG's embedded CSS. I find the current design fine, so I'll leave that tweaking up to you; I'd just like a chance to review that before merging?

**Review by avivace — APPROVED** [review]
Alright, merging this in the current state as I don't have bandwidth for the suggested style changes, I'll come back at them later

**Pull request merged**
