### PR TITLE
Serial Data Transfer: document disconnects

### PR DESCRIPTION
**Pull request by daid**
image

Measured on my CGB by shorting the serial in pin with ground and then release it. While the CGB is on.

Did not measure the DMG yet. So just as a draft right now.

### CODE REVIEW

**Comment by avivace** [comment]
@daid any update on this? Maybe we can start merging the CGB?

**Comment by daid** [comment]
Haven't found the means yet to measure the DMG, as I lack a link cable for it, and making the right connections directly on the connector pins didn't work out.

Want me to pull off the draft status to merge the CGB part of it?

**Comment by avivace** [comment]
> Haven't found the means yet to measure the DMG, as I lack a link cable for it, and making the right connections directly on the connector pins didn't work out.
> 
> Want me to pull off the draft status to merge the CGB part of it? I don't expect a very different result on the DMG.

I think we should start merging the CGB part

**Comment by avivace** [comment]
Hey @daid, do you have any news on this? Do you need any equipment?

**Review by avivace — APPROVED** [review]
I'm merging this due to inactivity/lack of follow up and I don't want to abandon this information here - feel free to open another PR/issue when you have updates @daid .

**Pull request merged**
